blank_issues_enabled: false
contact_links:
  - name: Report API issue
    url: https://weerlive.nl/over-weerlive-contact.php#contact
    about: Report issues related to the API.

  - name: API key request
    url: https://weerlive.nl/api/toegang/index.php
    about: Request your free API key.

  - name: API documentation
    url: https://weerlive.nl/delen.php
    about: Weerlive API documentation.

  - name: Weerlive library
    url: https://github.com/golles/python-weerlive
    about: Python library repository.
