name: Update copyright year(s) in license file

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 1 1 1 *"

permissions:
  contents: read

jobs:
  update-license-year:
    name: Update license year
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update license
        uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
